/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface CompatibilityFallbackHandler extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): CompatibilityFallbackHandler;
  clone(): CompatibilityFallbackHandler;
  methods: {
    NAME(): NonPayableTransactionObject<string>;

    VERSION(): NonPayableTransactionObject<string>;

    getMessageHash(
      message: string | number[]
    ): NonPayableTransactionObject<string>;

    getMessageHashForSafe(
      safe: string,
      message: string | number[]
    ): NonPayableTransactionObject<string>;

    getModules(): NonPayableTransactionObject<string[]>;

    "isValidSignature(bytes32,bytes)"(
      _dataHash: string | number[],
      _signature: string | number[]
    ): NonPayableTransactionObject<string>;

    "isValidSignature(bytes,bytes)"(
      _data: string | number[],
      _signature: string | number[]
    ): NonPayableTransactionObject<string>;

    onERC1155BatchReceived(
      arg0: string,
      arg1: string,
      arg2: (number | string | BN)[],
      arg3: (number | string | BN)[],
      arg4: string | number[]
    ): NonPayableTransactionObject<string>;

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: number | string | BN,
      arg3: number | string | BN,
      arg4: string | number[]
    ): NonPayableTransactionObject<string>;

    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: number | string | BN,
      arg3: string | number[]
    ): NonPayableTransactionObject<string>;

    simulate(
      targetContract: string,
      calldataPayload: string | number[]
    ): NonPayableTransactionObject<string>;

    supportsInterface(
      interfaceId: string | number[]
    ): NonPayableTransactionObject<boolean>;

    tokensReceived(
      arg0: string,
      arg1: string,
      arg2: string,
      arg3: number | string | BN,
      arg4: string | number[],
      arg5: string | number[]
    ): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
